### ISSUE TITLE
QA-Website Builder-User can't save the pages setting.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#326]
When we create the multiple layouts and then go to page setting and change the default layout to other layout and click on save button system do not perform any operation.refer below Error is showing in console window.

   at <anonymous>
_callee4$ @ PageSettings.vue:624
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
PageSettings.vue:624 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at VueComponent._callee4$ (https://www.webbuilder.qaflowz.tk/static/js/app.9d1c0c66c81444982e39.js:4461:61)
    at tryCatch (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:147721:40)
    at Generator.invoke [as _invoke] (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:147955:22)
    at Generator.prototype.(anonymous function) [as next] (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:147773:21)
    at step (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:20864:30)
    at https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:20875:13
    at <anonymous>

**Comment by fsaiyedOB** [comment]
Reproduced the case. Page settings are getting saved. Will check after pushing to QA

**Comment by acharotariya** [comment]
ok..setting's are saved now.working.
