### ISSUE TITLE
QA-Website Builder-Project creation does not work sometimes when we select the any other template also in website creation time.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-builder#331]
Project creation does not work sometimes when we select any other template in website creation time.

index.vue:5241 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of null
    at VueComponent._callee57$ (https://www.webbuilder.qaflowz.tk/static/js/app.9d1c0c66c81444982e39.js:17676:98)
    at tryCatch (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:147721:40)
    at Generator.invoke [as _invoke] (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:147955:22)
    at Generator.prototype.(anonymous function) [as next] (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:147773:21)
    at step (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:20864:30)
    at https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:20882:14
    at Promise (<anonymous>)
    at F (https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:21446:28)
    at https://www.webbuilder.qaflowz.tk/static/js/vendor.d95e00014e9f5f987de8.js:20861:12
    at VueComponent.checknameexist (https://www.webbuilder.qaflowz.tk/static/js/app.9d1c0c66c81444982e39.js:17715:8)

**Comment by fsaiyedOB** [comment]
The website is successfully getting created. No errors.

**Comment by fsaiyedOB** [comment]
Reproduced the case, bug with the subscription. Resolved.

**Comment by acharotariya** [comment]
ok...it's working fine.
